# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.CharField(max_length=200)),
                ('fac_name', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='facility_availability',
            name='fac_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Facility_master'),
        ),
    ]
