# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_setup',
            options={'verbose_name': 'Admin Setup', 'verbose_name_plural': 'Admin Setup'},
        ),
        migrations.AlterModelOptions(
            name='facility_availability',
            options={'verbose_name': 'Facility Availability', 'verbose_name_plural': 'Facility Availability'},
        ),
        migrations.AlterModelOptions(
            name='facility_master',
            options={'verbose_name': 'Add Facility', 'verbose_name_plural': 'Add Facility'},
        ),
        migrations.AlterField(
            model_name='facility_availability',
            name='day',
            field=models.CharField(max_length=20, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='facility_availability',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='facility_availability',
            name='fac_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Facility_master'),
        ),
        migrations.AlterField(
            model_name='facility_availability',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='facility_master',
            name='active',
            field=models.BooleanField(verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='facility_master',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facility_master',
            name='fac_id',
            field=models.CharField(max_length=200, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facility_master',
            name='fac_name',
            field=models.CharField(max_length=200, verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='facility_master',
            name='image',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='Image'),
        ),
    ]
