# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170710_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_setup',
        ),
    ]
