# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_delete_admin_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('event', models.CharField(blank=True, max_length=20, verbose_name='Event')),
                ('facility', models.CharField(max_length=200, verbose_name='Facility')),
                ('book_date', models.DateField(verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Start Time')),
                ('time_end', models.TimeField(verbose_name='End Time')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Booking',
                'verbose_name_plural': 'User Bookings',
            },
        ),
    ]
