# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_facility',
            name='facility',
            field=models.CharField(max_length=20, verbose_name='Facility'),
        ),
    ]
