# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_facility_availability_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_availability',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available:'),
        ),
        migrations.AlterField(
            model_name='facility_availability',
            name='day',
            field=models.DateField(verbose_name='Day'),
        ),
    ]
