# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20170716_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_facility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Facility_master'),
        ),
    ]
