# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20170717_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_facility',
            name='email',
        ),
    ]
